### PR TITLE
fixed retrieval of org-babel header parameters and added authentication with :username and :password parameters

### PR DESCRIPTION
**Pull request by ifitzpat**

### CODE REVIEW

**Comment by lanecodes** [comment]
Hi all,

It looks like there's work related to this project (e.g. <https://github.com/stardiviner/ob-cypher>, <https://github.com/Linusp/ob-cypher>) which build on this PR and would benefit from seeing it merged. I would also be interested in adding some documentation but not sure where is best to request to merge as I'd also be working with this PR in my history :grin:

Additionally I have the following suggestions for changes to this PR. I'm happy to work on them but not sure on the best way to contribute to a PR opened by someone else. What do we think?

## `port` rather than `http-port` passed to `ob-cypher/rest`

In `org-babel-execute:cypher` the value of `port` is passed to  `ob-cypher/rest` rather than `http-port`. As this value is then passed to `ob-cypher/query` which uses the Neo4j HTTP API, it seems the `http-port` is the correct parameter to pass here. @stardiviner does this in [this commit](https://github.com/stardiviner/ob-cypher/commit/7c483e97cd76449eb89a07b8c4dd8f13b205a073).

## Increment version number

Among other changes, this PR updates the package to send base64 encoded authorisation details to Neo4j via `authstring`. This fixes a bug which prevented me from using the package in Neo4j v3.5.5. Do we agree this justifies incrementing the version number to `0.0.2`?

## Add changelog

@stardiviner starts this [here](https://github.com/stardiviner/ob-cypher/commit/3c0b665309d8d79197d2646c79c30612cce4167a) and looks complete to me. @ifitzpat what do you think?

**Comment by ifitzpat** [comment]
It looks like there some interesting additions out there. Thanks for collating them @lanecodes! Perhaps it would be best to settle on one "main" repository for this package that can be actively maintained. I'm afraid I wouldn't be able to do it justice currently owing to a hectic work/life schedule. Is there anyone (perhaps @lanecodes?) willing to do the job? For my part, I'd be happy to review any work done to move the package forwards.
@zweifisch what is your perspective?

**Comment by stardiviner** [comment]
> Perhaps it would be best to settle on one "main" repository for this package that can be actively maintained.

I agree, this package need  to be maintained, collect other commits is useful.

**Comment by lanecodes** [comment]
Sounds good. Let's see what @zweifisch says in the next week or so. If we don't hear anything perhaps we could treat @ifitzpat's fork as the main repo for the sake of keeping things moving, and add a note to the README that it's a community fork which we'd be happy to merge with the MELPA recognised repo if possible.

If we do that I'd be happy to [take responsibility](https://help.github.com/en/github/administering-a-repository/transferring-a-repository) for the repo if that's alright with @ifitzpat. I'd appreciate your offer to review work though because I am conversant but not fluent in Emacs Lisp!

@stardiviner would you consider opening a PR to @ifitzpat 's `master` branch to incorporate your changelog and fix for the `port` - > `http-port` issue I mention above? Then if @zweifisch approves the merge on this PR then the fix will be incorporated. Otherwise it'll be part of the new main repo. Or does anyone have an idea for a better strategy?

**Comment by stardiviner** [comment]
@lanecodes Sure, I will create a PR for this fix.

___ UPDATE ___

I checked out my `master` branch, I found I have not just one `port` -> `http-port` commit. There are others. Should that be in PR too? Check them out:

https://github.com/stardiviner/ob-cypher/commits/master

**Comment by stardiviner** [comment]
Ok, I have created an PR on @ifitzpat 's repo. https://github.com/ifitzpat/ob-cypher/pull/2

BTW, if you want to maintain this package, You also need to tell MELPA to update recipe address to your repo. Express your reason. So that Emacs users can get the updates. Currently MELPA package version still is this one.

**Comment by lanecodes** [comment]
@stardiviner I suppose the key commits are [9e4860b](https://github.com/stardiviner/ob-cypher/commit/9e4860bd7068be881b1fcfe334b61301c71122b5) and [7c483e9](https://github.com/stardiviner/ob-cypher/commit/7c483e97cd76449eb89a07b8c4dd8f13b205a073) for the `http-port` parameter fix and [3c0b665](https://github.com/stardiviner/ob-cypher/commit/3c0b665309d8d79197d2646c79c30612cce4167a) for the changelog but I don't object to the formatting changes you've made in the other commits. They could have been a separate PR but not a problem if @ifitzpat is happy with it.

**Comment by stardiviner** [comment]
Because I don't know how to separate those commits with Git. So I did a mess PR. Sorry about this.

**Comment by lanecodes** [comment]
As I say it's no problem--don't worry about it! Keep this PR as you've done it, but for future reference what I'd do in this situation is use `git cherry-pick`:

Create feature branch `http-port-param` at @ifitzpat's last commit and check it out
```
git branch http-port-param 39598cc
git checkout http-port-param
```
Use `git cherry-pick` to select commits on your master branch for inclusion in the feature. I realise now that `9e4860b` corresponds to `76bd7bd` in @ifitzpat's work, so we just select `7c483e9`
```
git cherry-pick 7c483e9
```
Resolve any conflicts, save, and mark resolution with `git add ob-cypher.el`. Continue with the cherry-pick
```
git cherry-pick --continue
```
and the end result should be a new commit on branch `http-port-param` which does the same job as `7c483e9` but which can be applied directly on top of `39598cc`.

**Comment by stardiviner** [comment]
Thanks! @lanecodes

**Comment by ifitzpat** [comment]
Thanks, all! I'll see if I can test and merge later today

**Comment by stardiviner** [comment]
Hi, what's the status of this?

**Comment by lanecodes** [comment]
I've emailed @zweifisch this evening asking for their thoughts about being the future package maintainer. If we haven't head back by the end of the week I'd be comfortable opening a PR on MELPA which explains the situation and requests to update [this file](https://github.com/melpa/melpa/blob/master/recipes/ob-cypher) with the new fork. 

@ifitzpat please do have a look at @stardiviner's PR on your fork as that will be a step in the right direction whichever fork ends up being the main one going forward.

**Comment by zweifisch** [comment]
@lanecodes hi, invited you as collaborator. I no longer use neo4j.

**Comment by stardiviner** [comment]
@zweifisch That's great, it saved lot of time, so don't need to change MELPA repo and only merge PR works fine. Thanks a lot.

**Comment by stardiviner** [comment]
Ok, I'm a collaborator too now. Let's merge this first basic PR.

**Comment by stardiviner** [comment]
Then I checked my repo, how to merge my update? create an PR directly? I did a dry try, seems no conflict. But my code is based on @ifitzpat 's repo. Don't know this is suitble. @lanecodes  WDYT?

**Comment by ifitzpat** [comment]
You can try to rebase on zweifisch/master? Sorry for the slow response, guys! Hectic work schedule...

**Pull request merged**
